### ISSUE TITLE
Changing icons doesn't work

### ISSUE THREAD

**Issue by tjku** [fraserxu/ionic-rating#7]
Attributes `state-on`, `state-off` and `rating-states` doesn't work for me.

When I try to change default icons (to not to be stars), e.g. by writing
`<rating ng-model="x" state-on="'ion-thumbsup'" state-off="'ion-thumbsup'"></rating>`
or
`<rating ng-model="y" rating-states="ratingStates"></rating>`
this doesn't work. In first case, icons doesn't change, and in second case rating doesn't display at all (even default stars).

Apart from this, rating work just fine.

**Comment by tjku** [comment]
I've fixed this: #8

**Comment by martov1** [comment]
I still cant make it work using this line
<rating ng-model="x" state-on="'ion-thumbsup'" state-off="'ion-thumbsup'"></rating>

I see the rating with the default stars

**Comment by tux240** [comment]
Hi,

I would like to change stars icons but stateOn="fa fa-star" doesn't work for me.

I also see the rating with the default stars.

Any help ?

Thanks
